services:
  db:
    build: DB/    
    # ports:
    #  - "5432:5432"
    volumes:
      - db_vol:/var/lib/postgresql/data
    restart: always

  app:
    build: ./
    ports:
      - "4000:4000"
    #volumes:
     # - .:/app
    depends_on:
      - db
    restart: on-failure
volumes:
  db_vol: