services:
  db:
    build: DB/    
    volumes:
      - db_storage:/var/lib/postgresql/data
      - db_logs:/logs:z
    restart: always
    networks:
      - app_network
    env_file:
      - .env
    command: postgres -c port=$DB_PORT -c logging_collector=on -c log_destination=stderr -c log_directory=/logs

  app:
    build: ./
    ports:
      - "$PORT:$PORT"
    volumes:
     - .:/app    
    tty: true
    stdin_open: true
    depends_on:
      - db
    restart: on-failure
    networks:
      - app_network
volumes:
  db_storage:
  db_logs:
networks:
  app_network: